-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'certificate_attachment__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Certificate__c', 'Active__c', 'Document_Type__c', 'Subject__c'], live_ids_table='certificate_attachment__c__live_ids') }}
