-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'certificate_status__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Certificate__c', 'Status__c', 'Date_From__c', 'Date_of_Suspension__c', 'Date_To__c'], live_ids_table='certificate_status__c__live_ids') }}
