-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'contact', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'AccountId', 'Name', 'Phone', 'Email', 'HasOptedOutOfEmail', 'Public_Contact__c', 'Secondary_e_mail__c', 'Portal_Enabled__c', 'Portal_Username__c', 'Primary_Company_Contact_for_FSC__c'], live_ids_table='contact__live_ids') }}
