-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'country_data__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Continent__c', 'Country_code__c', 'ISO_Code__c', 'Name', 'Hemisphere__c'], live_ids_table='country_data__c__live_ids') }}
