-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'fsc_aaf_calculationses', 'fsc_aaf_calculationsid', 'modifiedon', has_soft_delete=False, live_ids_table='fsc_aaf_calculationses__live_ids') }}
