-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'non_certificate_holder__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Name', 'Organization__c', 'Contract_start_date__c', 'Contract_end_date__c', 'License_Status__c', 'policy_omit_trademark_symbols__c'], live_ids_table='non_certificate_holder__c__live_ids') }}
