-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'product_classification__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Name', 'Certificate__c', 'Main_Output_Category__c', 'Primary_Activity__c', 'Secondary_Activity__c', 'Trade_Name__c', 'Level_1__c', 'Level_2__c', 'Level_3__c', 'Regulatory_Module__c', 'CreatedDate'], live_ids_table='product_classification__c__live_ids') }}
