-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'product_species__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Genus__c', 'Product_Class__c', 'Species__c', 'CreatedDate'], live_ids_table='product_species__c__live_ids') }}
