-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'project_certificate__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Name', 'Application_Date__c', 'CB__c', 'Certificate_Status__c', 'Certification_Date__c', 'Certification_Type__c', 'Full_Code__c', 'Organization__c', 'Project_Country__c', 'Project_Name__c', 'Project_Scope__c', 'Project_Street__c', 'Project_Town_City__c', 'Standard__c'], live_ids_table='project_certificate__c__live_ids') }}
