-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'recordtype', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Name'], live_ids_table='recordtype__live_ids') }}
