-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'sales_history__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Audit_Period_From__c', 'Certificate__c', 'Sales_activity_Status__c', 'Sales_Activity_To__c'], live_ids_table='sales_history__c__live_ids') }}
