-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'species__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'Name', 'OwnerId'], live_ids_table='species__c__live_ids') }}
