-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by
-- listing this model in gen_silver.SKIP and hand-writing the file.
{{ silver_dedupe('bronze', 'transaction_verification_findings__c', 'Id', 'SystemModstamp', has_soft_delete=True, columns=['Id', 'CAR__c', 'Certificate_Relation__c', 'Description_Notes__c', 'Effective_Date__c', 'Finding__c', 'Name', 'Participating_Site__c'], live_ids_table='transaction_verification_findings__c__live_ids') }}
