"""Generate dbt silver models + sources from the bronze ENTITIES lists.

Keeps the "just add an entity name" promise: after adding a name to
sf_bronze.ENTITIES (and its columns to silver_config.SILVER_COLUMNS) or
dataverse_bronze.ENTITIES, run this to (re)generate the default silver model.

Each generated model:
  - dedupes to the latest row per primary key (by the incremental cursor),
  - drops Salesforce soft-deletes (IsDeleted),
  - anti-joins the <table>__live_ids snapshot to drop hard-deletes ("id 拉齐"),
  - projects only the configured business columns ("指定列"), dropping dlt columns.

Hand-written custom silver models (listed in SKIP) are never overwritten.

    python gen_silver.py
"""

import sf_bronze
import dataverse_bronze
from silver_config import published_columns

DBT_SILVER = "/home/ubuntu/dagster/dbt/models/silver"

# Entities whose silver model is hand-written (custom logic) — left alone.
SKIP = set()


def _model_name(table):
    return table[:-3] if table.endswith("__c") else table


def specs():
    """Yield (model_name, source_table, pk, cursor, has_soft_delete, has_live_ids)."""
    for entity in sf_bronze.ENTITIES:
        table = entity.lower()
        yield _model_name(table), table, "Id", sf_bronze._cursor_for(entity), True, True
    for entity_set, id_field in dataverse_bronze.ENTITIES.items():
        yield _model_name(entity_set), entity_set, id_field, "modifiedon", False, True


def _columns_literal(cols):
    return "[" + ", ".join(f"'{c}'" for c in cols) + "]"


def main():
    tables = []          # data tables (for _sources.yml)
    live_ids_tables = []  # live-ids snapshots (for _sources.yml + anti-join)
    for model, table, pk, cursor, hsd, hlids in specs():
        tables.append(table)
        live_ids = f"{table}__live_ids"
        if hlids:
            live_ids_tables.append(live_ids)
        if model in SKIP:
            print(f"skip (custom): {model}")
            continue

        cols = published_columns(table)
        columns_arg = f", columns={_columns_literal(cols)}" if cols else ""
        live_arg = f", live_ids_table='{live_ids}'" if hlids else ""
        sql = (
            f"-- AUTO-GENERATED by gen_silver.py — do not edit; add custom logic by\n"
            f"-- listing this model in gen_silver.SKIP and hand-writing the file.\n"
            f"{{{{ silver_dedupe('bronze', '{table}', '{pk}', '{cursor}', "
            f"has_soft_delete={hsd}{columns_arg}{live_arg}) }}}}\n"
        )
        with open(f"{DBT_SILVER}/{model}.sql", "w") as f:
            f.write(sql)
        n = len(cols) if cols else "all"
        print(f"wrote {model}.sql <- bronze.{table} (pk={pk}, cursor={cursor}, "
              f"soft_delete={hsd}, cols={n})")

    # regenerate the sources file covering every bronze data + live-ids table
    lines = ["version: 2", "", "sources:", "  - name: bronze", "    database: lake",
             "    schema: bronze", "    tables:"]
    lines += [f"      - name: {t}" for t in tables + live_ids_tables]
    with open(f"{DBT_SILVER}/_sources.yml", "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote _sources.yml ({len(tables)} data + {len(live_ids_tables)} live-ids tables)")


if __name__ == "__main__":
    main()
